### ISSUE TITLE
Are there any plans to publish artifacts for different scala/spark versions in Maven?

### ISSUE THREAD

**Issue by SemyonSinchenko** [Raiffeisen-DGTL/checkita-data-quality#13]

**Comment by gabb1er** [comment]
Hi Semen!

Yes, we are planning to add release publishing to Maven in the nearest future.

**Comment by gabb1er** [comment]
Hi, Semyon!

We are glad to announce that Checkita has been finally published to Maven Central. You can find published artifacts here: https://mvnrepository.com/artifact/org.checkita/checkita-core

In addition, we added more detailed information about releases in the project README. Please review corresponding section:
https://github.com/Raiffeisen-DGTL/checkita-data-quality?tab=readme-ov-file#releases-to-maven-central-repository
